### ISSUE TITLE
Level 21 Issue with mirror

### ISSUE THREAD

**Issue by zimmermant** [stared/quantum-game#10]
When the upper right mirror is in place as shown there is no interference at the beam splitter below it but interference does occur if the mirror is replaced with a beam splitter.

<img width="727" alt="screenshot 2017-12-20 08 39 36" src="https://user-images.githubusercontent.com/7947401/34212329-95e77794-e561-11e7-8aba-85bbf0003b9c.png">

**Comment by stared** [comment]
I am not sure what you mean. There is no interference when phases differ by pi/2, so it's expected behaviour.

**Comment by zimmermant** [comment]
The beam-splitter gives me the correct phase shift but the mirror does not.  In the first picture I've used the beam splitter which results in the light interfering at the beam-splitter circled in green and all of the light going to the detector to the right.  In the second picture I replace the beam-splitter with a mirror but don't see the correct interference at the circled beam splitter.  Shouldn't the phase shift from a mirror be the same as the phase shift from a beam-splitter?

<img width="698" alt="screenshot 2018-01-02 11 50 04" src="https://user-images.githubusercontent.com/7947401/34494009-06a506fc-efb4-11e7-8e11-8b3df46450dc.png">
<img width="694" alt="screenshot 2018-01-02 11 51 23" src="https://user-images.githubusercontent.com/7947401/34494017-0afe6298-efb4-11e7-9dcb-fb1bd327de7f.png">

**Comment by stared** [comment]
Please consult element encyclopedia, which explicitly shows reflection phases.

In short, for mirror phase is pi, while for this beam splitter it is pi/2 (and no phase shift for transmission). 

Well, all elements are up to a global phase. It's choice is somewhat arbitrary and I tried to made choices that are the most intuitive. (E.g. for sugar solution.) And alternative choice, would be to also set reflection from beam splitter to pi, but then for transmission it would need to be pi/2.

A physical picture for that would be:
For a plate with optical length of \lambda/4 you get reflection with phase pi interfering constructively with internal reflection (as it accumulated phase pi). Transmission is with phase pi/2.
