### ISSUE TITLE
Rotating doesn't work in Chrome

### ISSUE THREAD

**Issue by Liosan** [stared/quantum-game#5]
Clicking just causes mirrors to be dragged again. Works fine in Firefox.

**Comment by nubok** [comment]
I just wanted to report the same issue. To add additional information: Rotating the mirror works in Microsoft Edge.

**Comment by stared** [comment]
On my Chrome it works (Desktop, Chrome 58.0.3029.110, OSX 10.10.5).

Could you write which version you use?

**Comment by nubok** [comment]
Interestingly it now works on Google Chrome 58.0.3029.110 (64-bit) [Windows 10].

**Comment by Liosan** [comment]
Indeed, I can't reproduce this now either :) Weird. Clsoing.

**Comment by fake-name** [comment]
On Chrome 62.0.3202.94, I can't rotate the mirrors either.

**Comment by Sean-Brown** [comment]
I was able to reproduce this by prematurely stopping the simulation, here are the steps:

1. Press the laser
2. Click on the board while the laser is in-transit

Unfortunately now I can't seem to get it to rotate pieces again, even after a cache-clearing hard reset   :(

**Comment by stared** [comment]
I also have Chrome, but never experienced this problem. Maybe it is about MacBook Pro touchpad, which I have.

Created a work-around (b5bde3309ca92ceeb4c59f8ad63485ef7f775169).
Now small drags (not ending in the same tile) do rotate.

Does it help?

**Comment by Shantha1** [comment]
Could you show me how to get the solution for level 25?
